const express = require('express');
const router = express.Router();
const przedmiotyControler = require('../controllers/przedmiotyController');
router.get('/', przedmiotyControler.showPrzedmiotyList);
router.get('/add', przedmiotyControler.showAddPrzedmiotForm);
router.get('/edit/:przedId', przedmiotyControler.showEditPrzedmiotForm);
router.get('/details/:przedId', przedmiotyControler.showPrzedmiotDetails);
router.post('/add', przedmiotyControler.addPrzedmiot); 
router.post('/edit', przedmiotyControler.updatePrzedmiot);
router.get('/delete/:przedId', przedmiotyControler.deletePrzedmiot);
module.exports = router;