const express = require('express');
const router = express.Router();
const studenciControler = require('../controllers/studenciController');
router.get('/', studenciControler.showStudenciList);
router.get('/add', studenciControler.showAddStudentForm);
router.get('/edit/:studId', studenciControler.showEditStudentForm);
router.get('/details/:studId', studenciControler.showStudentDetails);
router.post('/add', studenciControler.addStudent); 
router.post('/edit', studenciControler.updateStudent);
router.get('/delete/:studId', studenciControler.deleteStudent);
module.exports = router;